# Generated by Django 4.2.7 on 2025-07-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Add unique constraint to email field
        migrations.RunSQL(
            sql="""
            CREATE UNIQUE INDEX IF NOT EXISTS auth_user_email_unique 
            ON auth_user (LOWER(email)) 
            WHERE email != '';
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS auth_user_email_unique;
            """
        ),
    ]
