# Generated by Django 4.2.7 on 2025-07-10 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Additional payment information'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Bank transfer reference or payment ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('processing', 'Payment Processing'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed'), ('refunded', 'Payment Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BankTransferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_image', models.ImageField(blank=True, upload_to='bank_transfers/')),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer', to='orders.order')),
            ],
        ),
    ]
