# Generated by Django 4.2.7 on 2025-07-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method_order_payment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransferdetails',
            name='nuban',
            field=models.CharField(blank=True, help_text='NUBAN (Nigerian Uniform Bank Account Number)', max_length=20),
        ),
        migrations.AlterField(
            model_name='banktransferdetails',
            name='iban',
            field=models.CharField(blank=True, help_text='IBAN for international transfers', max_length=50),
        ),
        migrations.AlterField(
            model_name='banktransferdetails',
            name='routing_number',
            field=models.CharField(blank=True, help_text='Sort Code (for UK) or Routing Number (for US)', max_length=20),
        ),
        migrations.AlterField(
            model_name='banktransferdetails',
            name='swift_code',
            field=models.CharField(blank=True, help_text='SWIFT/BIC code for international transfers', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('ussd', 'USSD Payment'), ('mobile_money', 'Mobile Money'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='card', max_length=20),
        ),
    ]
