# Generated by Django 4.2.7 on 2025-07-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_banktransferdetails_nuban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransferdetails',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes for verification process'),
        ),
    ]
