# Generated by Django 4.2.7 on 2025-07-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_banktransferdetails_verification_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('ussd', 'USSD Payment'), ('mobile_money', 'Mobile Money')], default='card', max_length=20),
        ),
    ]
